version: '3.4'

services:

  web-app:
    image: christianacca/aspnetcoreapp-netfx-sample:${VERSION:-latest}
    build:
        context: src
        dockerfile: MRI.DataGateway.Horizon.TokenProvider/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"

networks:
  default:
    external:
      name: nat