version: '3.4'

services:

  web-app:
    image: christianacca/aspnetcoreapp-simple-sample:${VERSION:-latest}
    build:
        context: src
        dockerfile: Demo.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development

# workaround to local dev machine which cannot create new virtual network adapter's
networks:
  default:
    external:
      name: nat