version: '3.4'

services:

  web-app:
    image: christianacca/aspnetcoreapp-netfx-sample:${VERSION:-latest}
    build:
        context: src
        dockerfile: Demo.API/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    external:
      name: nat